# Generated by Django 6.0.3 on 2026-06-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('date', models.DateField(help_text='Date of the event')),
                ('start_time', models.TimeField(help_text='Event start time')),
                ('end_time', models.TimeField(help_text='Event end time')),
                ('location', models.CharField(help_text='Event venue/location', max_length=300)),
                ('max_volunteers', models.PositiveIntegerField(default=50, help_text='Maximum number of volunteers needed')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the event', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Event banner/image', null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, help_text='When the volunteer checked in', null=True)),
                ('check_out', models.DateTimeField(blank=True, help_text='When the volunteer checked out', null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(help_text='The volunteer this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='volunteers.volunteerprofile')),
                ('event', models.ForeignKey(help_text='The event this attendance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'volunteer')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='When the volunteer was assigned')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('event', models.ForeignKey(help_text='The event this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('volunteer', models.ForeignKey(help_text='The volunteer assigned to this event', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Volunteer Assignment',
                'verbose_name_plural': 'Volunteer Assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('event', 'volunteer')},
            },
        ),
    ]
