# Generated by Django 6.0.3 on 2026-06-14 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('open_for_interest', 'Open for Interest'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the event', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Event Assignment'), ('interest_cancelled', 'Interest Cancelled by Admin'), ('general', 'General Announcement')], default='general', max_length=30)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Full notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Related event (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event')),
                ('recipient', models.ForeignKey(help_text='The user receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the volunteer expressed interest')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if the volunteer cancelled their interest')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the volunteer cancelled their interest', null=True)),
                ('event', models.ForeignKey(help_text='The event the volunteer is interested in', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='events.event')),
                ('volunteer', models.ForeignKey(help_text='The volunteer who expressed interest', on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to='volunteers.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Event Interest',
                'verbose_name_plural': 'Event Interests',
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'volunteer')},
            },
        ),
    ]
