# Generated by Django 6.0.3 on 2026-06-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('date_of_birth', models.DateField(help_text='Date of birth (YYYY-MM-DD)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], help_text='Gender identity', max_length=20)),
                ('address', models.TextField(help_text='Full street address')),
                ('city', models.CharField(help_text='City of residence', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('education', models.CharField(help_text='Highest educational qualification', max_length=200)),
                ('skills', models.TextField(help_text='List your skills (e.g., Teaching, First Aid, Social Media)')),
                ('interests', models.TextField(help_text='Areas of interest (e.g., Education, Healthcare, Environment)')),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('both', 'Both Weekdays & Weekends'), ('flexible', 'Flexible')], default='flexible', help_text='When are you available to volunteer?', max_length=20)),
                ('resume', models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX)', null=True, upload_to='resumes/')),
                ('photo', models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current application status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True)),
                ('volunteer_id', models.CharField(blank=True, help_text='Unique volunteer ID (auto-generated upon approval)', max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account linked to this volunteer profile', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer Profile',
                'verbose_name_plural': 'Volunteer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
